### ISSUE TITLE
Error in `ngmlr': double free or corruption (!prev): 0x00002aaed8eeb910

### ISSUE THREAD

**Issue by MikeWLloyd** [philres/ngmlr#92]
I am trying to run PacBio data against a mouse genome, and am seeing the following error `Error in `ngmlr': double free or corruption (!prev): 0x00002aaed8eeb910`. I am running the alignment with a singularity container: `quay.io-biocontainers-ngmlr-0.2.7--he513fc3_2.img`

Here is the entire log of the crash:  

```
Processed: 1345640 (0.74), R/S: 13.61, RL: 24060, Time: 3.00 1.00 88.00, Align: 0.94, 999, 0.85
Debug: PositionNM reallocated.
Debug: PositionNM reallocated.
Debug: PositionNM reallocated.
*** Error in `ngmlr': double free or corruption (!prev): 0x00002aaed8eeb910 ***
======= Backtrace: =========
/lib/libc.so.6(+0x750fb)[0x2aaaab2630fb]
/lib/libc.so.6(+0x7ac36)[0x2aaaab268c36]
/lib/libc.so.6(+0x7b9b3)[0x2aaaab2699b3]
ngmlr(_ZN6Convex15ConvexAlignFast19checkMdBufferLengthEiR5Aligni+0x63)[0x555555580ea3]
ngmlr(_ZN6Convex15ConvexAlignFast12convertCigarEPKciR5AlignRNS0_10FwdResultsEii+0x54e)[0x55555558140e]
ngmlr(_ZN6Convex15ConvexAlignFast11SingleAlignEiP12CorridorLineiPKcS4_R5AligniiPv+0x230)[0x555555583960]
ngmlr(_ZN15AlignmentBuffer16computeAlignmentEPK8IntervaliPKcmiiiPK10MappedReadbbb+0x8d4)[0x555555589ca4]
ngmlr(_ZN15AlignmentBuffer13alignIntervalEPK10MappedReadPK8IntervalPKcmbb+0x15e)[0x55555558a0de]
ngmlr(_ZN15AlignmentBuffer7realignEiPK8IntervalPS0_S3_P10MappedReadP5AlignRiP13LocationScorei+0xdb7)[0x55555558b717]
ngmlr(_ZN15AlignmentBuffer30alignSingleOrMultipleIntervalsEP10MappedReadPK8IntervalP13LocationScoreP5AlignRi+0x5d3)[0x55555558f3b3]
ngmlr(_ZN15AlignmentBuffer18processLongReadLISEP9ReadGroup+0x25da)[0x55555559654a]
ngmlr(_ZN11ScoreBuffer5DoRunEv+0x1e4)[0x5555555a2794]
ngmlr(_ZN11ScoreBuffer7addReadEP10MappedReadi+0x63)[0x5555555a2953]
ngmlr(_ZN2CS7RunReadEP10MappedReadPFvmymmPvEP11ScoreBufferP15AlignmentBuffer+0x16f)[0x55555557e42f]
ngmlr(_ZN2CS5DoRunEv+0x786)[0x55555557f016]
ngmlr(_ZN7NGMTask3RunEv+0xd)[0x555555586acd]
ngmlr(_ZN4_NGM10ThreadFuncEPv+0x1b)[0x55555558599b]
/lib/libpthread.so.0(+0x81da)[0x2aaaaacd51da]
/lib/libc.so.6(clone+0x6d)[0x2aaaab2d78ed]
======= Memory map: ========
2aaaaaaab000-2aaaaaacb000 r-xp 00000000 07:00 143                        /lib/ld-2.18.so
2aaaaaacb000-2aaaaaacd000 r-xp 00000000 00:00 0                          [vdso]
2aaaaaacd000-2aaaaaace000 rw-p 00000000 00:00 0
2aaaaaace000-2aaaaaad1000 r--p 00000000 07:00 403                        /usr/local/lib/libz.so.1.2.11
2aaaaaad1000-2aaaaaadf000 r-xp 00003000 07:00 403                        /usr/local/lib/libz.so.1.2.11
2aaaaaadf000-2aaaaaae5000 r--p 00011000 07:00 403                        /usr/local/lib/libz.so.1.2.11
2aaaaaae5000-2aaaaaae6000 ---p 00017000 07:00 403                        /usr/local/lib/libz.so.1.2.11
2aaaaaae6000-2aaaaaae7000 r--p 00017000 07:00 403                        /usr/local/lib/libz.so.1.2.11
2aaaaaae7000-2aaaaaae8000 rw-p 00018000 07:00 403                        /usr/local/lib/libz.so.1.2.11
2aaaaaae8000-2aaaaaaea000 rw-p 00000000 00:00 0
2aaaaaaea000-2aaaaab8c000 r--p 00000000 07:00 393                        /usr/local/lib/libstdc++.so.6.0.27
2aaaaab8c000-2aaaaac0b000 r-xp 000a2000 07:00 393                        /usr/local/lib/libstdc++.so.6.0.27
2aaaaac0b000-2aaaaac4c000 r--p 00121000 07:00 393                        /usr/local/lib/libstdc++.so.6.0.27
2aaaaac4c000-2aaaaac57000 r--p 00161000 07:00 393                        /usr/local/lib/libstdc++.so.6.0.27
2aaaaac57000-2aaaaac5b000 rw-p 0016c000 07:00 393                        /usr/local/lib/libstdc++.so.6.0.27
2aaaaac5b000-2aaaaac5f000 rw-p 00000000 00:00 0
2aaaaac5f000-2aaaaac62000 r--p 00000000 07:00 379                        /usr/local/lib/libgcc_s.so.1
2aaaaac62000-2aaaaac6e000 r-xp 00003000 07:00 379                        /usr/local/lib/libgcc_s.so.1
2aaaaac6e000-2aaaaac71000 r--p 0000f000 07:00 379                        /usr/local/lib/libgcc_s.so.1
2aaaaac71000-2aaaaac72000 r--p 00011000 07:00 379                        /usr/local/lib/libgcc_s.so.1
2aaaaac72000-2aaaaac73000 rw-p 00012000 07:00 379                        /usr/local/lib/libgcc_s.so.1
2aaaaac73000-2aaaaac77000 rw-p 00000000 00:00 0
2aaaaacca000-2aaaaaccb000 r--p 0001f000 07:00 143                        /lib/ld-2.18.so
2aaaaaccb000-2aaaaaccc000 rw-p 00020000 07:00 143                        /lib/ld-2.18.so
2aaaaaccc000-2aaaaaccd000 rw-p 00000000 00:00 0
2aaaaaccd000-2aaaaace6000 r-xp 00000000 07:00 163                        /lib/libpthread-2.18.so
2aaaaace6000-2aaaaaee5000 ---p 00019000 07:00 163                        /lib/libpthread-2.18.so
2aaaaaee5000-2aaaaaee6000 r--p 00018000 07:00 163                        /lib/libpthread-2.18.so
2aaaaaee6000-2aaaaaee7000 rw-p 00019000 07:00 163                        /lib/libpthread-2.18.so
2aaaaaee7000-2aaaaaeeb000 rw-p 00000000 00:00 0
2aaaaaeeb000-2aaaaafec000 r-xp 00000000 07:00 155                        /lib/libm-2.18.so
2aaaaafec000-2aaaab1ec000 ---p 00101000 07:00 155                        /lib/libm-2.18.so
2aaaab1ec000-2aaaab1ed000 r--p 00101000 07:00 155                        /lib/libm-2.18.so
2aaaab1ed000-2aaaab1ee000 rw-p 00102000 07:00 155                        /lib/libm-2.18.so
2aaaab1ee000-2aaaab391000 r-xp 00000000 07:00 146                        /lib/libc-2.18.so
2aaaab391000-2aaaab591000 ---p 001a3000 07:00 146                        /lib/libc-2.18.so
2aaaab591000-2aaaab595000 r--p 001a3000 07:00 146                        /lib/libc-2.18.so
2aaaab595000-2aaaab597000 rw-p 001a7000 07:00 146                        /lib/libc-2.18.so
2aaaab597000-2aaafc6b1000 rw-p 00000000 00:00 0
2aaafc6b1000-2aaafc6b2000 ---p 00000000 00:00 0
2aaafc6b2000-2aaafc8b2000 rw-p 00000000 00:00 0
2aaafc8b2000-2aaafc8b3000 ---p 00000000 00:00 0
2aaafc8b3000-2aaafcab3000 rw-p 00000000 00:00 0
2aaafcab3000-2aaafcab4000 ---p 00000000 00:00 0
2aaafcab4000-2aaafccb4000 rw-p 00000000 00:00 0
2aaafccb4000-2aaafccb5000 ---p 00000000 00:00 0
2aaafccb5000-2aaafceb5000 rw-p 00000000 00:00 0
2aaafceb5000-2aaafceb6000 ---p 00000000 00:00 0
2aaafceb6000-2aaafd0b6000 rw-p 00000000 00:00 0
2aaafd0b6000-2aaafd0b7000 ---p 00000000 00:00 0
2aaafd0b7000-2aaafd2b7000 rw-p 00000000 00:00 0
2aaafd2b7000-2aaafd2b8000 ---p 00000000 00:00 0
2aaafd2b8000-2aaafd4b8000 rw-p 00000000 00:00 0
2aaafd4b8000-2aaafd4b9000 ---p 00000000 00:00 0
2aaafd4b9000-2aaafd6b9000 rw-p 00000000 00:00 0
2aaafd6b9000-2aaafd6ba000 ---p 00000000 00:00 0
2aaafd6ba000-2aaafd8ba000 rw-p 00000000 00:00 0
2aaafd8ba000-2aaafd8bb000 ---p 00000000 00:00 0
2aaafd8bb000-2aaafdabb000 rw-p 00000000 00:00 0
2aaafdabb000-2aaafdabc000 ---p 00000000 00:00 0
2aaafdabc000-2aaafdcbc000 rw-p 00000000 00:00 0
2aaafdcbc000-2aaafdcbd000 ---p 00000000 00:00 0
2aaafdcbd000-2aaafdebd000 rw-p 00000000 00:00 0
2aaafdebd000-2aaafdebe000 ---p 00000000 00:00 0
2aaafdebe000-2aaafe0be000 rw-p 00000000 00:00 0
2aaafe0be000-2aaafe0bf000 ---p 00000000 00:00 0
2aaafe0bf000-2aaafe2bf000 rw-p 00000000 00:00 0
2aaafe2bf000-2aaafe2c0000 ---p 00000000 00:00 0
2aaafe2c0000-2aaafe4c0000 rw-p 00000000 00:00 0
2aaafe4c0000-2aaafe4c1000 ---p 00000000 00:00 0
2aaafe4c1000-2aaafe6c1000 rw-p 00000000 00:00 0
2aaafe6c1000-2aaafe6c2000 ---p 00000000 00:00 0
2aaafe6c2000-2aaafe942000 rw-p 00000000 00:00 0
2aaafe942000-2aaafe943000 ---p 00000000 00:00 0
2aaafe943000-2aaafeb43000 rw-p 00000000 00:00 0
2aaafeb43000-2aaafeb44000 ---p 00000000 00:00 0
2aaafeb44000-2aaafee08000 rw-p 00000000 00:00 0
2aaafee08000-2aaafee09000 ---p 00000000 00:00 0
2aaafee09000-2aaaff009000 rw-p 00000000 00:00 0
2aaaff009000-2aaaff00a000 ---p 00000000 00:00 0
2aaaff00a000-2aaaff20a000 rw-p 00000000 00:00 0
2aaaff20a000-2aaaff20b000 ---p 00000000 00:00 0
2aaaff20b000-2aaaff40b000 rw-p 00000000 00:00 0
2aaaff40b000-2aaaff40c000 ---p 00000000 00:00 0
2aaaff40c000-2aaaff6d0000 rw-p 00000000 00:00 0
2aaaff6d0000-2aaaff6d1000 ---p 00000000 00:00 0
2aaaff6d1000-2aaafffb5000 rw-p 00000000 00:00 0
2aab00000000-2aab017c9000 rw-p 00000000 00:00 0
2aab017c9000-2aab04000000 ---p 00000000 00:00 0
2aab04000000-2aab0a953000 rw-p 00000000 00:00 0
2aab0c6b2000-2aabeef45000 rw-p 00000000 00:00 0
2aabf0000000-2aabf178c000 rw-p 00000000 00:00 0
2aabf178c000-2aabf4000000 ---p 00000000 00:00 0
2aabf6f45000-2aac21024000 rw-p 00000000 00:00 0
2aac24000000-2aac25841000 rw-p 00000000 00:00 0
2aac25841000-2aac28000000 ---p 00000000 00:00 0
2aac29024000-2aac53103000 rw-p 00000000 00:00 0
2aac54000000-2aac55817000 rw-p 00000000 00:00 0
2aac55817000-2aac58000000 ---p 00000000 00:00 0
2aac5b103000-2aac751e1000 rw-p 00000000 00:00 0
2aac78000000-2aac7996d000 rw-p 00000000 00:00 0
2aac7996d000-2aac7c000000 ---p 00000000 00:00 0
2aac7c000000-2aaca60df000 rw-p 00000000 00:00 0
2aaca8000000-2aaca9824000 rw-p 00000000 00:00 0
2aaca9824000-2aacac000000 ---p 00000000 00:00 0
2aacac000000-2aacd60df000 rw-p 00000000 00:00 0
2aacd8000000-2aacd9743000 rw-p 00000000 00:00 0
2aacd9743000-2aacdc000000 ---p 00000000 00:00 0
2aacdc000000-2aad060df000 rw-p 00000000 00:00 0
2aad08000000-2aad09842000 rw-p 00000000 00:00 0
2aad09842000-2aad0c000000 ---p 00000000 00:00 0
2aad0c000000-2aad4a0e1000 rw-p 00000000 00:00 0
2aad4c000000-2aad4dc1f000 rw-p 00000000 00:00 0
2aad4dc1f000-2aad50000000 ---p 00000000 00:00 0
2aad50000000-2aad660dd000 rw-p 00000000 00:00 0
2aad68000000-2aad697a4000 rw-p 00000000 00:00 0
2aad697a4000-2aad6c000000 ---p 00000000 00:00 0
2aad6e0dd000-2aad981bc000 rw-p 00000000 00:00 0
2aad9c000000-2aad9d835000 rw-p 00000000 00:00 0
2aad9d835000-2aada0000000 ---p 00000000 00:00 0
2aada01bc000-2aadca29b000 rw-p 00000000 00:00 0
2aadcc000000-2aadcd6be000 rw-p 00000000 00:00 0
2aadcd6be000-2aadd0000000 ---p 00000000 00:00 0
2aadd229b000-2aadfc37a000 rw-p 00000000 00:00 0
2aae00000000-2aae018e6000 rw-p 00000000 00:00 0
2aae018e6000-2aae04000000 ---p 00000000 00:00 0
2aae0437a000-2aae3e45a000 rw-p 00000000 00:00 0
2aae40000000-2aae418af000 rw-p 00000000 00:00 0
2aae418af000-2aae44000000 ---p 00000000 00:00 0
2aae4645a000-2aae60538000 rw-p 00000000 00:00 0
2aae64000000-2aae657c4000 rw-p 00000000 00:00 0
2aae657c4000-2aae68000000 ---p 00000000 00:00 0
2aae68538000-2aae92617000 rw-p 00000000 00:00 0
2aae94000000-2aae95918000 rw-p 00000000 00:00 0
2aae95918000-2aae98000000 ---p 00000000 00:00 0
2aae9a617000-2aaeb4578000 rw-p 00000000 00:00 0
2aaec46f6000-2aaed46f7000 rw-p 00000000 00:00 0
2aaed8000000-2aaed9810000 rw-p 00000000 00:00 0
2aaed9810000-2aaedc000000 ---p 00000000 00:00 0
2aaedc6f7000-2aaee6657000 rw-p 00000000 00:00 0
2aaef67d5000-2aaf067d6000 rw-p 00000000 00:00 0
2aaf08000000-2aaf098c8000 rw-p 00000000 00:00 0
2aaf098c8000-2aaf0c000000 ---p 00000000 00:00 0
2aaf0e7d6000-2aaf18736000 rw-p 00000000 00:00 0
2aaf288b4000-2aaf388b5000 rw-p 00000000 00:00 0
2aaf3c000000-2aaf3d855000 rw-p 00000000 00:00 0
2aaf3d855000-2aaf40000000 ---p 00000000 00:00 0
2aaf408b5000-2aaf4a815000 rw-p 00000000 00:00 0
2aaf5c000000-2aaf5d92d000 rw-p 00000000 00:00 0
2aaf5d92d000-2aaf60000000 ---p 00000000 00:00 0
2aaf62993000-2aaf7c8f4000 rw-p 00000000 00:00 0
2aaf8ca72000-2aaf9ca73000 rw-p 00000000 00:00 0
2aafa0000000-2aafa18b4000 rw-p 00000000 00:00 0
2aafa18b4000-2aafa4000000 ---p 00000000 00:00 0
2aafa4a73000-2aafae9d3000 rw-p 00000000 00:00 0
2aafbeb51000-2aafceb52000 rw-p 00000000 00:00 0
2aafd0000000-2aafd1890000 rw-p 00000000 00:00 0
2aafd1890000-2aafd4000000 ---p 00000000 00:00 0
2aafd6b52000-2aafe0ab2000 rw-p 00000000 00:00 0
2aaff0c30000-2ab000c31000 rw-p 00000000 00:00 0
2ab004000000-2ab0058f8000 rw-p 00000000 00:00 0
2ab0058f8000-2ab008000000 ---p 00000000 00:00 0
2ab008c31000-2ab012b91000 rw-p 00000000 00:00 0
2ab022d0f000-2ab032d10000 rw-p 00000000 00:00 0
2ab034000000-2ab03577f000 rw-p 00000000 00:00 0
2ab03577f000-2ab038000000 ---p 00000000 00:00 0
2ab03ad10000-2ab044c70000 rw-p 00000000 00:00 0
2ab054dee000-2ab085ff1000 rw-p 00000000 00:00 0
2ab0ad3da000-2ab0d29b9000 rw-p 00000000 00:00 0
2ab0f2b14000-2ab1172d4000 rw-p 00000000 00:00 0
2ab12d5eb000-2ab189c16000 rw-p 00000000 00:00 0
2ab1a6595000-2ab21617f000 rw-p 00000000 00:00 0
555555554000-555555567000 r--p 00000000 07:00 358                        /usr/local/bin/ngmlr
555555567000-5555555a9000 r-xp 00013000 07:00 358                        /usr/local/bin/ngmlr
5555555a9000-5555555b8000 r--p 00055000 07:00 358                        /usr/local/bin/ngmlr
5555555b8000-5555555ba000 r--p 00063000 07:00 358                        /usr/local/bin/ngmlr
5555555ba000-5555555bb000 rw-p 00065000 07:00 358                        /usr/local/bin/ngmlr
5555555bb000-555555b84000 rw-p 00000000 00:00 0                          [heap]
7ffffffde000-7ffffffff000 rw-p 00000000 00:00 0                          [stack]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
/pod/2/SVE/PacBio/work/db/51aa9730b4ec7609855c0a8fca3d66/.command.sh: line 2: 94219 Aborted                 ngmlr -t 24 --bam-fix -r Mus_musculus_akrj.AKR_J_v1.dna.toplevel.fa -q m64119_201120_172541.fastq.gz -o m64119_201120_172541.fastq.sam
SIGABRT: abort
PC=0x473c4b m=0 sigcode=0

goroutine 1 [running, locked to thread]:
syscall.RawSyscall(0x3e, 0x16fdc, 0x6, 0x0, 0xc0001cdef0, 0x49de52, 0x16fdc)
	/usr/lib64/go-1.11.1/src/syscall/asm_linux_amd64.s:78 +0x2b fp=0xc0001cdeb8 sp=0xc0001cdeb0 pc=0x473c4b
syscall.Kill(0x16fdc, 0x6, 0x4388ee, 0xc0001cdf20)
	/usr/lib64/go-1.11.1/src/syscall/zsyscall_linux_amd64.go:597 +0x4b fp=0xc0001cdf00 sp=0xc0001cdeb8 pc=0x4705bb
github.com/sylabs/singularity/internal/app/starter.Master.func2()
	internal/app/starter/master_linux.go:152 +0x3e fp=0xc0001cdf38 sp=0xc0001cdf00 pc=0x7395ee
github.com/sylabs/singularity/internal/pkg/util/mainthread.Execute.func1()
	internal/pkg/util/mainthread/mainthread.go:21 +0x2f fp=0xc0001cdf60 sp=0xc0001cdf38 pc=0x737dff
main.main()
	cmd/starter/main_linux.go:102 +0x5f fp=0xc0001cdf98 sp=0xc0001cdf60 pc=0x91a51f
runtime.main()
	/usr/lib64/go-1.11.1/src/runtime/proc.go:201 +0x207 fp=0xc0001cdfe0 sp=0xc0001cdf98 pc=0x430bb7
runtime.goexit()
	/usr/lib64/go-1.11.1/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc0001cdfe8 sp=0xc0001cdfe0 pc=0x45c601

goroutine 5 [syscall]:
os/signal.signal_recv(0xaf7ba0)
	/usr/lib64/go-1.11.1/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
	/usr/lib64/go-1.11.1/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/lib64/go-1.11.1/src/os/signal/signal_unix.go:29 +0x41

goroutine 7 [chan receive]:
github.com/sylabs/singularity/internal/pkg/util/mainthread.Execute(0xc0002f42c0)
	internal/pkg/util/mainthread/mainthread.go:24 +0xb4
github.com/sylabs/singularity/internal/app/starter.Master(0x7, 0x4, 0x16ff1, 0xc00000d220)
	internal/app/starter/master_linux.go:151 +0x405
main.startup()
	cmd/starter/main_linux.go:75 +0x4b8
created by main.main
	cmd/starter/main_linux.go:98 +0x35

rax    0x0
rbx    0x0
rcx    0xffffffffffffffff
rdx    0x0
rdi    0x16fdc
rsi    0x6
rbp    0xc0001cdef0
rsp    0xc0001cdeb0
r8     0x0
r9     0x0
r10    0x0
r11    0x206
r12    0x30
r13    0x11
r14    0xaecd54
r15    0x0
rip    0x473c4b
rflags 0x206
cs     0x33
fs     0x0
gs     0x0
```

Any ideas as to what causes this, or what I can check to debug? 

Thanks.

**Comment by fritzsedlazeck** [comment]
Thanks for reaching out. Are these HiFi reads or CLR reads?  I am also a bit in the dark about what could have caused this. I assume memory availability wasn't an issue in this run?
Thanks
Fritz

**Comment by MikeWLloyd** [comment]
Fritz, 

It is HiFi reads. I am mapping to a draft genome, which has a number of small contigs. I am thinking this may be the cause. I am going to try to remove those smaller contigs and re-run the mapping. If this is the case, will let you know.

**Comment by fritzsedlazeck** [comment]
Thanks Mike,
that can be it... Please keep me posted. 
Cheers
Fritz
